# Generated by Django 4.1.7 on 2023-03-30 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_joinusform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_type', models.CharField(choices=[('1', 'Workers_houses'), ('2', 'Galleries'), ('3', 'Farm')], max_length=100)),
                ('building_age', models.FloatField(blank=True, null=True)),
                ('building_area', models.FloatField(blank=True, null=True)),
                ('key_place', models.CharField(blank=True, max_length=256, null=True)),
                ('building_category', models.CharField(choices=[('1', 'Housing'), ('2', 'Commercial'), ('3', 'Agricultural'), ('4', 'Industrial')], max_length=100)),
                ('price', models.FloatField(blank=True, null=True)),
                ('soom_price', models.FloatField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
