# Generated by Django 4.1.7 on 2023-03-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_building'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name': 'العقارات', 'verbose_name_plural': 'العقارات'},
        ),
        migrations.AlterModelOptions(
            name='contactform',
            options={'verbose_name': 'طلبات التواصل', 'verbose_name_plural': 'طلبات التواصل'},
        ),
        migrations.AlterModelOptions(
            name='joinusform',
            options={'verbose_name': 'طلبات الانضمام', 'verbose_name_plural': 'طلبات الانضمام'},
        ),
        migrations.AddField(
            model_name='building',
            name='building_usage',
            field=models.CharField(choices=[('1', 'Singles'), ('2', 'Families'), ('3', 'Office')], default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='offer',
            field=models.CharField(choices=[('1', 'Singles'), ('2', 'Families'), ('3', 'Auction')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactform',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='البريد الالكتروني'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='message',
            field=models.TextField(verbose_name='الرسالة'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='name',
            field=models.CharField(max_length=100, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='رقم الهاتف'),
        ),
    ]
