# Generated by Django 4.1.7 on 2023-03-31 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_building_options_alter_contactform_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='Central_air_conditioning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='building',
            name='apartments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='baths',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='car_entrance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='building',
            name='city',
            field=models.CharField(choices=[('1', 'حفر الباطن'), ('2', 'حائل'), ('3', 'الرياض'), ('4', 'الدمام'), ('5', 'بريدة')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='design_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='driver_room',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='electricity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='building',
            name='elevators',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='extension',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='floors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='gas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='building',
            name='ground_floor_rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='hall',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='kitchen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='building',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='mez_hall',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='building',
            name='parking',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='piece_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='pieces',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='building',
            name='region',
            field=models.CharField(choices=[('1', 'المنطقة الشرقية'), ('2', 'حائل'), ('3', 'الرياض'), ('4', 'الدمام'), ('5', 'القصيم')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='rooftop',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='sauna',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='building',
            name='seperated_2_floors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='building',
            name='seperated_entrance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='building',
            name='shared_entrance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='building',
            name='split_air_conditioner',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='upper_floor_rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='warehouse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='building',
            name='well',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='building',
            name='window_air_conditioner',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BuildingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='building_images/')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.building')),
            ],
        ),
    ]
