# Generated by Django 4.1.7 on 2023-03-31 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_building_central_air_conditioning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='neighborhood',
            field=models.CharField(choices=[('1', 'المحمدية'), ('2', 'الكهيفية'), ('3', 'الريان'), ('4', 'النهضة'), ('5', 'بريدة')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
