# Generated by Django 4.1.7 on 2023-04-13 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_building_neighborhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='building_category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='building',
            name='building_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='building',
            name='building_usage',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='building',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='offer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='building',
            name='region',
            field=models.CharField(max_length=100),
        ),
    ]
