# Generated by Django 4.1.7 on 2023-04-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_building_building_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractRequestForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('city', models.CharField(max_length=100, verbose_name='المدينة')),
                ('contract_duration', models.CharField(max_length=100, verbose_name='مدة العقد')),
                ('contract_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع العقد')),
                ('region', models.CharField(max_length=100)),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'العقد الالكتروني',
                'verbose_name_plural': 'العقود الالكترونية',
            },
        ),
    ]
