# Generated by Django 4.1.7 on 2023-06-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_building_building_notes_building_building_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildingimage',
            options={'verbose_name': 'صور العقار', 'verbose_name_plural': 'صور العقار'},
        ),
        migrations.AddField(
            model_name='building',
            name='electricity_meter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='furnished',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='pieces_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='plan_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='roof',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='servant_room',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='shops',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='state',
            field=models.CharField(blank=True, choices=[('1', 'معلق'), ('2', 'تمت الموافقة عليه')], default='1', max_length=1, null=True, verbose_name='حالة الطلب'),
        ),
        migrations.AddField(
            model_name='building',
            name='steam_bath',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='units_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='water_meter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='Central_air_conditioning',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='building_category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='تصنيف العقار'),
        ),
        migrations.AlterField(
            model_name='building',
            name='building_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='building_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='building_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع العقار'),
        ),
        migrations.AlterField(
            model_name='building',
            name='building_usage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='car_entrance',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='electricity',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='gas',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='kitchen',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='mez_hall',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='offer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='pool',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='sauna',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='seperated_2_floors',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='seperated_entrance',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='shared_entrance',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='warehouse',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='well',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
