# Generated by Django 4.1.7 on 2023-06-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_buildingimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='driver_room',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
